baseURL = "https://tsukubar.org/"
languageCode = "ja-JP"
title = "Tsukuba.R"
theme = "minimal"
relativeURLs = true
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
#disqusShortname = "username" # delete this to disable disqus comments
#googleAnalytics = ""

[params]
    author = "Tsukuba.R Community"
    profilePic = "https://raw.githubusercontent.com/tsukubar/resources/master/logo/tsukubar-logo_square-800x800.png"
    description = "A Data Science and R Study Group for Tsukuba"
    githubUsername = "tsukubar"
    accent = "#54447B"
    showBorder = true
    backgroundColor = "white"
    font = "Open Sans" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "github"
    highlightLanguages = ["r", "python", "bash"]

[[menu.main]]
    url = "https://tsukubar.org/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/events/"
    name = "Events"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Blog"
    weight = 3

[[menu.main]]
    url = "/teams/"
    name = "Our Team"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://github.com/tsukubar/"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/tsukubar/"
    name = "twitter"
    weight = 2
    
[[menu.icon]]
    url = "https://www.meetup.com/ja-JP/TsukubaR/"
    name = "meetup"
    weight = 3

[[menu.icon]]
    url = "https://r-wakalang.slack.com/messages/CCKFP8U0L/"
    name = "slack"
    weight = 4
